#PURPOSE: Run RERconverge correlations on log-transformed phenotype data as a BINARY TRAIT; convergent shifts to lower RTM based on l1ou considered foreground branches

library(RERconverge)
library(ggtree)
dataset<-"OUmodel"
print("Correlating RERs with log-transformed phenotype data as a BINARY TRAIT")
print(paste("Dataset name:", dataset))

print("Read in data...")
#Read in trees for individual alignments that match the master species tree topology (generated by script 05_make_trees.r)
myTrees<-readTrees("trees_for_RERconverge.noBlanks.tree")
#Read in phenotype data
myData<-read.csv("/uufs/chpc.utah.edu/common/HIPAA/u6035720/MURINAE/murine_repro_pheno_data_RTM.formatted.csv", header=TRUE)
myPheno<-log(myData$RTM)
names(myPheno)<-myData$tree_sample_name

print("Setting foreground branches...")
#Set foreground branches
#Based on l1ou OU model with BIC, random root, and RR method for determining convergence
#fg<-c("Hyomys_goliath_ABTC42697", "Pseudomys_novaehollandiae_ABTC08140", "Pseudomys_delicatulus_U1509", "Pseudomys_shortridgei_Z25113", "Notomys_alexis_U1308","Notomys_fuscus_M22830","Notomys_mitchellii_M21518","Zyzomys_pedunculatus_Z34925", "Eropeplus_canus_NMVZ21733", "Paruromys_dominator_JAE4870", "Bandicota_indica_ABTC119185","Nesokia_indica_ABTC117074"
#sisters_fg<-list("clade1"=c("Pseudomys_novaehollandiae_ABTC08140","Pseudomys_delicatulus_U1509"), "clade2"=c("Notomys_alexis_U1308","Notomys_fuscus_M22830"), "clade3"=c("clade2","Notomys_mitchellii_M21518"), "clade4"=c("Eropeplus_canus_NMVZ21733","Paruromys_dominator_JAE4870"), "clade5"=c("Bandicota_indica_ABTC119185","Nesokia_indica_ABTC117074"))
#OLD FOREGROUNDS - Before adding additional Breed data
fg<-c("Pseudomys_novaehollandiae_ABTC08140", "Pseudomys_delicatulus_U1509", "Notomys_alexis_U1308","Notomys_fuscus_M22830","Notomys_mitchellii_M21518","Zyzomys_pedunculatus_Z34925", "Bandicota_indica_ABTC119185","Nesokia_indica_ABTC117074")
sisters_fg<-list("clade1"=c("Pseudomys_novaehollandiae_ABTC08140","Pseudomys_delicatulus_U1509"), "clade2"=c("Notomys_alexis_U1308","Notomys_fuscus_M22830"), "clade3"=c("clade2","Notomys_mitchellii_M21518"), "clade4"=c("Bandicota_indica_ABTC119185","Nesokia_indica_ABTC117074"))
print("Foregrounds:")
print(fg)
#Based on lowest 20% quantile
#q20<-quantile(myPheno, .2)
#fg<-names(myPheno)[which(myPheno < q20)]
#print(fg)
#sisters_fg<-list("clade1"=c("Pseudomys_novaehollandiae_ABTC08140","Pseudomys_delicatulus_U1509"), "clade2"=c("Notomys_alexis_U1308","Notomys_fuscus_M22830"), "clade3"=c("clade2","Notomys_mitchellii_M21518"), "clade4"=c("Bandicota_indica_ABTC119185","Nesokia_indica_ABTC117074"))
#Based on lowest 10% quantile
#q10<-quantile(myPheno, .1)
#fg<-names(myPheno)[which(myPheno < q10)]
#print(fg)
#sisters_fg<-list("clade1"=c("Notomys_alexis_U1308","Notomys_fuscus_M22830"), "clade2"=c("clade1","Notomys_mitchellii_M21518"), "clade3"=c("Bandicota_indica_ABTC119185","Nesokia_indica_ABTC117074"))
#Based on 80% quantile (highest 20%)
#q80<-quantile(myPheno, .8)
#fg<-names(myPheno)[which(myPheno > q80)] #GREATER THAN!!!
#print(fg)
#sisters_fg<-list("clade1"=c("Pogonomys_macrourus_ABTC43144", "Chiruromys_vates_ABTC43096"), "clade2"=c("clade1", "Lorentzimys_nouhuysi_ABTC-46314")) #Rattus tunneyi, leucopus, and lutreolus are w/in same clade of rattus but not reciprocally monophyletic w/ smaller testes species, so not grouping them as a sister clade 
#Based on 90% quantile (highest 10%)
#q90<-quantile(myPheno, .9)
#fg<-names(myPheno)[which(myPheno > q90)] #GREATER THAN!!!
#print(fg)
#sisters_fg<-list("clade1"=c("Pogonomys_macrourus_ABTC43144", "Chiruromys_vates_ABTC43096"), "clade2"=c("clade1", "Lorentzimys_nouhuysi_ABTC-46314"))
#Based on 50% quantile (lowest 50%)
#q50<-quantile(myPheno, .5)
#fg<-names(myPheno)[which(myPheno < q50)] #LESS THAN!!!
#print(fg)
#sisters_fg<-list("clade1"=c("Pseudomys_novaehollandiae_ABTC08140","Pseudomys_delicatulus_U1509"), "clade2"=c("Notomys_alexis_U1308","Notomys_fuscus_M22830"), "clade3"=c("clade2","Notomys_mitchellii_M21518"), "clade4"=c("clade3", "Notomys_cervinus_M22857"), "clade5"=c("Pseudomys_albocinereus_WAMM18855", "Pseudomys_apodemoides_M16672"), "clade6"=c("Pseudomys_desertor_ABTC41464", "Pseudomys_shortridgei_Z25113"), "clade7"=c("Bandicota_indica_ABTC119185","Nesokia_indica_ABTC117074"), "clade8"=c("Zyzomys_argurus_ABTC61630","Zyzomys_maini_ABTC07900"), "clade9"=c("Mus_caroli_10460X9","Mus_musculus-musculus_10460X14"), "clade10"=c("clade9","Mus_minutoides_10460X2"), "clade11"=c("Rattus_argentiventer_LSUMZ38199","Rattus_hoffmanni_LSUMZ39187"), "clade12"=c("clade11","rnor6"), "clade13"=c("Rattus_colletti_RAT25","Rattus_villosissimus_sample1"))
#Based on 50% quantile (highest 50%)
#q50<-quantile(myPheno, .5)
#fg<-names(myPheno)[which(myPheno > q50)] #GREATER THAN!!!
#print(fg)
#sisters_fg<-list("clade1"=c("Pogonomys_macrourus_ABTC43144", "Chiruromys_vates_ABTC43096"), "clade2"=c("clade1", "Lorentzimys_nouhuysi_ABTC-46314"),  "clade3"=c("Leggadina_forresti_WAMM62323","Leggadina_lakedownensis_WAMM21623"), "clade4"=c("Bunomys_andrewsi_sample1","Bunomys_chrysocomus_JAE4867"), "clade5"=c("Paucidentomys_vermidax_Z21914","Tateomys_macrocercus_Z21834"), "clade6"=c("Maxomys_musschenbroekii_sample1","Maxomys_surifer_JAE3632"))

fgTree<-foreground2TreeClades(fg, sisters_fg, myTrees, plotTree=F)
pdf(paste("RERconverge_output.logRTM_binary",dataset,"foreground_tree.pdf", sep="."), height=15, width=12)
plotTreeHighlightBranches(fgTree, hlspecies=fgTree$edge[which(fgTree$edge.length==1),2], hlcols="red", main="High RTM foreground branches", useGG=TRUE)
dev.off()

print("Calculating all residuals and correlations...")
#Calculating paths from the foreground tree
pathvec<-tree2PathsClades(fgTree, myTrees)
#Calculate RERs
pdf(paste("RERconverge_output.logRTM_binary",dataset,"heteroskedacity_plot.RTMspeciesOnly.pdf", sep="."))
#CUTOFF 0 - will not filter out any short branches
#useSpecies only includes species w/ RTM data available
myRER<-getAllResiduals(myTrees, useSpecies=names(myPheno), transform="sqrt", weighted=T, scale=T, cutoff=0)
#CUTOFF DEFAULT - will do the default calculation to remove short branches
#useSpecies only includes species w/ RTM data available
#myRER<-getAllResiduals(myTrees, useSpecies=names(myPheno), transform="sqrt", weighted=T, scale=T)
dev.off()

# Calculate correlation
res<-correlateWithBinaryPhenotype(myRER, pathvec, min.sp=10, min.pos=2, weighted="auto")
print(head(res))
#order correlation statistics by corrected p-value and save in csv file
res_pSort<-res[order(res$p.adj),]
write.csv(res_pSort, file=paste("RERconverge_output.logRTM_binary_residuals",dataset,"RTMspeciesOnly.csv", sep="."), row.names=TRUE)
#Save some variables here just in case permulations fail, so we don't need to rerun everything if they do
save(myTrees, fgTree, pathvec, myRER, res, file=paste("RERconverge_output.logRTM_binary",dataset,"RTMspeciesOnly.rds", sep="."))

q()

print("Running permulations...")
#Run permulations
#define the root species and master tree
myRoot<-c("Lophiomys_imhausi_UM5152", "Lophuromys_woosnami_LSUMZ37793")
masterTree<-myTrees$masterTree
#perform binary complete case (CC) permulation
permCC<-getPermsBinary(numperms=1000, fg_vec=fg, sisters_list=sisters_fg, root_sp=myRoot, RERmat=myRER, trees=myTrees, mastertree=masterTree, permmode="cc")
permpvalCC<-permpvalcor(res,permCC)
print(head(permpvalCC))
write.table(permpvalCC, file=paste("RERconverge_output.logRTM_binary_permpvalCC",dataset,"RTMspeciesOnly.txt", sep="."))
#producing one permulated tree using CC permulation - I think this is what I will need for phyloConverge input
treeCC<-simBinPhenoCC(myTrees, masterTree, myRoot, fg, sisters_fg, pathvec, plotTreeBool=F)
pdf(paste("RERconverge_output.logRTM_binary",dataset,"permCC_tree.RTMspeciesOnly.pdf", sep="."))
plotTreeHighlightBranches(treeCC,hlspecies=which(treeCC$edge.length==1), hlcols="red", useGG=TRUE)
dev.off()

#Append permulation results to main results table
res$permpval<-permpvalCC[match(rownames(res), names(permpvalCC))]
res$permpvaladj<-p.adjust(res$permpval, method="BH")
write.csv(res_pSort, file=paste("RERconverge_output.logRTM_binary_residuals_withPermCC",dataset,"RTMspeciesOnly.csv", sep="."), row.names=TRUE)

#Save data
save(myTrees, fgTree, pathvec, myRER, res, permCC, treeCC, file=paste("RERconverge_output.logRTM_binary",dataset,"RTMspeciesOnly.rds", sep="."))

print("Done with 07.2_get_RERs_binary.r")
